spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      create-drop
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  h2:
    console:
      enabled: true